[tool.poetry]
name = "car-calculator"
version = "0.1.0"
description = ""
authors = ["Madhav Achar <acharmd@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
